create table "public"."recipe_name_alias" (
    "id" bigint generated by default as identity not null,
    "recipe_id" bigint not null,
    "alias" text not null default ''::text,
    "company_id" bigint not null
);


alter table "public"."recipe_name_alias" enable row level security;

CREATE UNIQUE INDEX recipe_name_alias_alias_key ON public.recipe_name_alias USING btree (alias);

CREATE UNIQUE INDEX recipe_name_alias_id_key ON public.recipe_name_alias USING btree (id);

alter table "public"."recipe_name_alias" add constraint recipe_name_alias_pkey primary key using index "recipe_name_alias_id_key";

alter table "public"."recipe_name_alias" add constraint public_recipe_name_alias_company_id_fkey foreign key (company_id) references company (id) on update cascade on delete cascade;

alter table "public"."recipe_name_alias" add constraint recipe_name_alias_recipe_id_fkey foreign key (recipe_id) references recipe (id) on update cascade on delete cascade;

alter table "public"."recipe_name_alias" add constraint recipe_name_alias_alias_check check ((length(alias) < 100));

create policy "Admin can do anything within company"
on "public"."recipe_name_alias"
as permissive
for all
to authenticated
using ((( SELECT worker_for_current_user.is_admin
   FROM worker_for_current_user) AND ( SELECT (worker_for_current_user.company_id = recipe_name_alias.company_id)
   FROM worker_for_current_user)));

CREATE POLICY "Non-admin can select on recipe_name_alias, within company"
ON "public"."recipe_name_alias"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
  (SELECT (worker_for_current_user.company_id = recipe_name_alias.company_id)
   FROM worker_for_current_user)
);

CREATE POLICY "Non-admin can insert on recipe_name_alias, within company"
ON "public"."recipe_name_alias"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (
  (SELECT (worker_for_current_user.company_id = recipe_name_alias.company_id)
   FROM worker_for_current_user)
);

CREATE POLICY "Non-admin can update on recipe_name_alias, within company"
ON "public"."recipe_name_alias"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (
  (SELECT (worker_for_current_user.company_id = recipe_name_alias.company_id)
   FROM worker_for_current_user)
);

GRANT ALL PRIVILEGES ON TABLE "public"."recipe_name_alias" TO "authenticated";
GRANT ALL PRIVILEGES ON TABLE "public"."recipe_name_alias" TO "service_role";