create table "public"."product_name_alias" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint not null,
    "alias" text not null default ''::text,
    "company_id" bigint not null
);


alter table "public"."product_name_alias" enable row level security;

CREATE UNIQUE INDEX product_name_alias_pkey ON public.product_name_alias USING btree (id);

alter table "public"."product_name_alias" add constraint "product_name_alias_pkey" PRIMARY KEY using index "product_name_alias_pkey";

alter table "public"."product_name_alias" add constraint "public_product_name_alias_company_id_fkey" FOREIGN KEY (company_id) REFERENCES company(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."product_name_alias" validate constraint "public_product_name_alias_company_id_fkey";

alter table "public"."product_name_alias" add constraint "public_product_name_alias_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."product_name_alias" validate constraint "public_product_name_alias_product_id_fkey";

create policy "Admin can do anything within company"
on "public"."product_name_alias"
as permissive
for all
to authenticated
using ((( SELECT worker_for_current_user.is_admin
   FROM worker_for_current_user) AND ( SELECT (worker_for_current_user.company_id = product_name_alias.company_id)
   FROM worker_for_current_user)));

CREATE POLICY "Non-admin can select on product_name_alias, within company"
ON "public"."product_name_alias"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
  (SELECT (worker_for_current_user.company_id = product_name_alias.company_id)
   FROM worker_for_current_user)
);

CREATE POLICY "Non-admin can insert on product_name_alias, within company"
ON "public"."product_name_alias"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (
  (SELECT (worker_for_current_user.company_id = product_name_alias.company_id)
   FROM worker_for_current_user)
);

CREATE POLICY "Non-admin can update on product_name_alias, within company"
ON "public"."product_name_alias"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (
  (SELECT (worker_for_current_user.company_id = product_name_alias.company_id)
   FROM worker_for_current_user)
);

GRANT ALL PRIVILEGES ON TABLE "public"."product_name_alias" TO "authenticated";
GRANT ALL PRIVILEGES ON TABLE "public"."product_name_alias" TO "service_role";